### ISSUE TITLE
Data frames

### ISSUE THREAD

**Issue by Eflores89** [alanjordan101/USPresDebates#1]
Alan, can you please upload the data.frames you need help parsing/cleaning ?

**Comment by Eflores89** [comment]
never mind, just saw it...

**Comment by alanjordan101** [comment]
Hey Eduardo,
If you're going to edit debate Rdata files, start from 1960 and work forward please.Also give them a different name so I don't overwrite them. I have a tendency to modify the step 2 programs and run them as batch, overwriting the existing files. I have to work on 2012 and 2016. I'm sure there are enough problems in 1960-2008 to keep you busy.
I'll be honest, I don't really understand how github works as far as versioning and forks go.  

```
On Friday, January 22, 2016 3:15 PM, Eduardo Flores <notifications@github.com> wrote:
```

 never mind, just saw it... —

**Comment by Eflores89** [comment]
Hi, no problem.

I'll see what I can fix, and let you know.
