### ISSUE TITLE
Import gist

### ISSUE THREAD

**Issue by Eflores89** [alanjordan101/USPresDebates#4]
I've made this small code to import the "old-format" debates here: https://gist.github.com/Eflores89/f993474caff7b4bcdee2

I think it makes more sense to work on the overall, as opposed to going debate by debate, or what do you think?

**Comment by alanjordan101** [comment]
I find the overall overwhelming. 
I'm making tables for each election and linking them by person. When I'm done, I could rbind those election year tables and link them by person, year to full_debate table and get the same result.

I haven't run it but I have a few questions.

Where does archivos come from? n <- length(archivos)
Is that something that only works in the Spanish version or is archivos defined somewhere else?

I'm not sure about the cleaning up that's done inside. The - that start sentences are handy. They tell you it's an incomplete sentence and to exclude the sentence fragment from Fleisch-Kincaid and SMOG reading level analysis.

The transcripts are in many different formats and you can't assume that the first line is a description of the debate.

It looks handy though.
Sorry, I'm sick at the moment. Talk later.

**Comment by Eflores89** [comment]
Yep, I guess I had an overload of information today. I see where this is coming from, I'll see if I can work on a random debate, and try to make a function or set of functions that "cleans" this debate, this way, we can work really fast on the other ones. 

as for the `archivos`, sorry about that, it's a typo, it should be: `a`

**Comment by alanjordan101** [comment]
That sounds really helpful :) 

```
On Tuesday, January 26, 2016 10:43 PM, Eduardo Flores <notifications@github.com> wrote:
```

 Yep, I guess I had an overload of information today. I see where this is coming from, I'll see if I can work on a random debate, and try to make a function or set of functions that "cleans" this debate, this way, we can work really fast on the other ones. as for the archivos, sorry about that, it's a typo, it should be: a—
